### ISSUE TITLE
[BUG] Issue with opening on Windows

### ISSUE THREAD

**Issue by ItsUrPapi12** [Spacexplorer11/Space_Dodge#7]
### Bug Description

#helpwanted 

So i can't open on windows since i followed all the instructions on it and etc and when i open it terminal opens for about 0.5 Seconds and then closes 

- Pavi 
   - Your QA Tester

### Reproduction Steps

Honestly just get a windows and follow the tutorial and when you try to open the main.py it doesn't work

### Expected Outcome

Its meant to open instantly and allow window users to play just like mac users

### Screenshots

![Screenshot 2024-10-18 171102](https://github.com/user-attachments/assets/e9034f99-f4c1-4538-af04-99b05b3c1879)
![Screenshot 2024-10-18 171112](https://github.com/user-attachments/assets/733970f1-0c13-499d-a3bf-1786222022cb)
![Screenshot 2024-10-18 171122](https://github.com/user-attachments/assets/09d2ba7f-096e-4d1b-ac92-ad6ce0b349b8)

**Comment by Spacexplorer11** [comment]
Hello, thank you for making an issue, I would like you to download the latest version of Space Dodge as this should solve your issue, but if it doesn't please let me know! Thank you!

**Comment by Spacexplorer11** [comment]
Hi @ItsUrPapi12, could you please open and run the **newest version** of my game in the default **IDLE** on Windows, and maybe provide a **screenshot** of an error message( if it occurs)?
**Thank you!**
##
>[!important]
Please make sure you run the `main.py` file in the IDLE and not any other file.

**Comment by Spacexplorer11** [comment]
The latest commit of my game fixes the issue as it has been tested on Windows, please download it, but do open a new issue if it doesn't work!
